# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d9239a1b49cfb923ab8fd000fe68b710c2aa436219fdc48bd2598a39fb60a2babc10ea1228c9b482016a951875976c3b96480e7d75058a4c19404011c3cc729

test:
  secret_key_base: 4d74c769f303da9580a98e4f5470940ce7ad20d0757b4a5af70565b9f0b61fd9a8373e68aa0d029d234ad2dc83c27dc7a5156ed977be9367344ab83ed7164362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
